users:
  columns:
  - name: id
    type: INTEGER
    constraints:
    - PRIMARY KEY
  - name: name
    type: TEXT
    constraints:
    - NOT NULL
students:
  columns:
  - name: id
    type: INTEGER
    constraints:
    - PRIMARY KEY
    - AUTOINCREMENT
  - name: name
    type: TEXT
    constraints:
    - NOT NULL
  - name: age
    type: INTEGER
    constraints: []
  - name: gender
    type: TEXT
    constraints: []
  - name: grade
    type: TEXT
    constraints:
    - NOT NULL
  - name: email
    type: TEXT
    constraints:
    - NOT NULL
    - UNIQUE
  - name: phone
    type: TEXT
    constraints:
    - NOT NULL
    - UNIQUE
  - name: address
    type: TEXT
    constraints:
    - NOT NULL
  - name: cgpa
    type: REAL
    constraints: []
  - name: enrollment_year
    type: INTEGER
    constraints: []
