[theme]
base="dark" 
primaryColor="#f3e5c3"  # Vanilla Latte for highlights (buttons, links)
backgroundColor="#0f1b1b"  # Deep Teal for the main background
secondaryBackgroundColor="#174e4f"  # Teal Forest for sidebar and containers
textColor="#f3e5c3"  # White text for readability
font="sans serif"
